language: rust
cache: cargo
rust:
- stable
- beta
- nightly
os:
- linux
- osx
- windows
matrix:
  allow_failures:
  - rust: nightly
before_script:
- rustup update
- rustup component add clippy-preview
script:
- cargo clippy -- --deny=warnings
- export RUSTFLAGS="-D warnings"; cargo build --verbose
- export RUSTFLAGS="-D warnings"; cargo test --verbose
before_deploy:
- cargo doc
- cargo package
deploy:
  provider: releases
  api_key:
    secure: NI7jNVRF19tKOgaRktecQ4dmNcFIfhlInwi+iwbjPnnwJHc2KCA03+BQPEwCBe2Zr7kuu6r+xqntsQTmEzu71iUn7UseKbhBq+VoisUBLpgzTuk/LnmfGbuT79N50bClskKfkIhESodLJf2vxrDuFloZPqPlyXjGjg80q04o6Ds2e8tqsEm4zHW4msOF2vo1voH9wGV00Z6DkAtUE1bu+Uco5iMHhYl9BytbT1tE2+CsZKOvejXYs/120bqJR9XKTg+snq+GxuX7CL+rk0u9E8quF03e279R1fWB+6taRcc0JZEYCPsJ2JMZXkM3iy8kBsn4IHbIp7wmK8BQn/NyKis4uJwwmshsiPpA7DwO6pxICX6lcCmX8KzwwGveoX64susOquN5odjU9aa8t0MoGgKBdYJ6uoH7tTctEyE0QlUst0EZYBuAxkI4dBUqoC9Lf5ZnePA6aNVejZ1dI+Jxf/Y8WleYF6NxHYQmHpgo3PD+wSBHR8GaUCMZp7oMLzaF1bSiMHagA3GbSo57F3cVg0aRSovmbtHTHIuXfpCM8OtK9FbrkrjWs3k92EKDH3ahjwdHGRm7hohSa9Z8Jna0GrdpTTDGXLppFEyxt4Xq1jNo9x+KgiJcmnXJAdb0/3ciFhEXWjBtBD0GHisY3efYcDwgWIWu69xN3pXObZFHBEg=
  on:
    tags: true
    repo: solana-labs/rbpf
    branch: solana-master
after_deploy:
- cargo publish --token "$CRATES_IO_TOKEN"
